tunnel: 19a0d6e6-ba48-4f34-b424-5a0911967d5a
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: dash.${DOMAIN}
    service: http://traefik:80

  - hostname: api.${DOMAIN}
    service: http://traefik:80

  - service: http_status:404
